"""
artixinstall.lib.pacman
~~~~~~~~~~~~~~~~~~~~~~~~

Artix pacman.conf writer.

Artix uses its own repository structure that differs from Arch:

    Artix repos (required)
        [system]      – base system packages
        [world]       – most user packages (replaces Arch's [extra])
        [galaxy]      – community-contributed (replaces Arch's [community])
        [lib32]       – 32-bit compat libs (optional)

    Arch compatibility repos (optional – for packages not in Artix)
        [extra]       – Arch extra (may pull systemd deps; use carefully)
        [community]   – Arch community

IMPORTANT
    The [core], [extra], [community] Arch repos MUST NOT be placed *before*
    Artix repos or systemd packages will shadow Artix equivalents.
    The correct order is: Artix repos first, then (optional) Arch repos.

Usage
-----
    from artixinstall.lib.pacman import write_artix_pacman_conf
    write_artix_pacman_conf(target=Path('/mnt'))
"""

from __future__ import annotations

from pathlib import Path
import logging as _logging
_log = _logging.getLogger("artixinstall.pacman")
debug = _log.debug; info = _log.info


# Default Artix mirrors.  On the live Artix ISO these are already configured;
# this module only writes a new conf when the installer is run from a non-Artix
# environment (e.g. testing from an Arch live ISO).
_ARTIX_MIRRORLIST = "/etc/pacman.d/mirrorlist-artix"
_ARCH_MIRRORLIST  = "/etc/pacman.d/mirrorlist"

_PACMAN_CONF_TEMPLATE = """\
# /etc/pacman.conf – generated by artixinstall
# Do not edit manually; re-run artixinstall to regenerate.

[options]
HoldPkg     = pacman glibc
Architecture = auto

Color
CheckSpace
ParallelDownloads = 5
VerbosePkgLists

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# ─────────────────────────────────────────
# Artix Linux repositories
# These MUST come before any Arch repos.
# ─────────────────────────────────────────

[system]
Include = {artix_mirrorlist}

[world]
Include = {artix_mirrorlist}

[galaxy]
Include = {artix_mirrorlist}

{lib32_section}

# ─────────────────────────────────────────
# Arch Linux compatibility repos  (optional)
# Packages here may depend on systemd.
# Only install from these repos consciously.
# ─────────────────────────────────────────

{arch_extra_section}
"""

_LIB32_SECTION = """\
[lib32]
Include = {artix_mirrorlist}
"""

_ARCH_EXTRA_SECTION = """\
# [extra]
# Include = {arch_mirrorlist}

# [community]
# Include = {arch_mirrorlist}
"""


def write_artix_pacman_conf(
    target: Path,
    include_lib32: bool = False,
    include_arch_compat: bool = False,
) -> Path:
    """
    Write /etc/pacman.conf inside *target* for Artix.

    Parameters
    ----------
    target:
        Chroot root (e.g. ``Path('/mnt')``).
    include_lib32:
        Enable the [lib32] repository.
    include_arch_compat:
        Uncomment the Arch [extra] / [community] repos (for packages
        not yet available in Artix repos).

    Returns
    -------
    Path
        Path to the written pacman.conf.
    """
    conf_path = target / "etc" / "pacman.conf"
    conf_path.parent.mkdir(parents=True, exist_ok=True)

    lib32 = _LIB32_SECTION.format(artix_mirrorlist=_ARTIX_MIRRORLIST) \
            if include_lib32 else ""

    arch_extra = (
        _ARCH_EXTRA_SECTION
        .format(arch_mirrorlist=_ARCH_MIRRORLIST)
        .replace("# [", "[").replace("# Include", "Include")  # uncomment
        if include_arch_compat
        else _ARCH_EXTRA_SECTION.format(arch_mirrorlist=_ARCH_MIRRORLIST)
    )

    content = _PACMAN_CONF_TEMPLATE.format(
        artix_mirrorlist=_ARTIX_MIRRORLIST,
        lib32_section=lib32,
        arch_extra_section=arch_extra,
    )

    conf_path.write_text(content)
    info(f"Wrote Artix pacman.conf → {conf_path}")
    return conf_path


def write_artix_mirrorlist(target: Path, mirrors: list[str] | None = None) -> Path:
    """
    Write /etc/pacman.d/mirrorlist-artix inside *target*.

    If *mirrors* is None, a set of default Artix mirrors is used.
    """
    default_mirrors = [
        "Server = https://mirror.pascalpuffke.de/artix-linux/$repo/os/$arch",
        "Server = https://ftp.myrveln.se/pub/linux/artix/$repo/os/$arch",
        "Server = https://artix.ldev.hu/$repo/os/$arch",
        "Server = https://www.artixlinux.org/packages/$repo/os/$arch",
    ]
    mirror_lines = "\n".join(mirrors or default_mirrors)

    ml_dir = target / "etc" / "pacman.d"
    ml_dir.mkdir(parents=True, exist_ok=True)
    ml_path = ml_dir / "mirrorlist-artix"
    ml_path.write_text(
        "# Artix Linux mirrors – generated by artixinstall\n"
        f"{mirror_lines}\n"
    )
    debug(f"Wrote Artix mirrorlist → {ml_path}")
    return ml_path
